feat: ['feature/*', 'feat/*']
fix: ['fix/*', 'bugfix/*', 'bug/*']
chore: ['chore/*', 'maintenance/*']
docs: ['docs/*', 'documentation/*']
style: ['style/*']
refactor: ['refactor/*']
test: ['test/*', 'testing/*']
build: ['build/*']
ci: ['ci/*']
perf: ['perf/*', 'performance/*']